var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                       ^                        ",
   "                                                       x                        ",
   "                                                     x x x                      ",
   "                                                     x o x                      ",
   "                                                    xxxxxxx                     ",
   "       xx                           o o                x                        ",
   "      xxxx                           ^            x  xx!xx  x                   ",
   "    xxx  xxx                     x xxxxx        x      v      x         x^x     ",
   "   xx      xx                 #  x!x            o             o        x   x    ",
   "  xx        xx                   xxx      o^o  xxx           xxx      xx   xx   ",
   "xxx          xxx                          xxx                      xxxxxxxxxxxxx",
   "  xxxx    xxxx    =    xxx    xx xx      xxxxx                       x       x  ",
   "  x          x       x  x  x    o            x      xxx xxx          x       x  ",
   "  x  @       o     ^x   o       ^          x o x                         o   x  ",
   "  x#xxxxxxxxxx^x^xxxxxxxxxxxx        xxxxxxxxxxxx             xxx#xxxxxxxxxxxx  ",
   "                            x!!!!!!!!x          xx!!!!!!!!!!!xx                 ",
   "                            x!!!!!!!!x           xx!!!!!!!!!xx                  ",
   "                            x!!!!!!!!x            xx!!!!!!!xx                   ",
   "                            xxxxxxxxxx             xxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     xxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x  ",
   "x                      x       x      x!!xxxxxxxxxxxxxxxxxxxxxxx           xxx                               x!x  ",
   "x          #           x       x      xx!!!!!!!!!!xx o x             o      x                                x!x  ",
   "x                      x       x       xxxxxxxxxx!!x                                              o   o   o  x!x  ",
   "x                      x   o   x                xx!xxxxxxxxxxx                         xxxx                  x!x  ",
   "x        xxxxx         x       x                 x!x         x  xxx xxx xxx        ^          xxxxxx^xxx^xxxx!!x  ",
   "x                      x       x                 xvx         x                  xxxxxxx  !!!!!!!!!!!!!!!!!!!!!xx  ",
   "x          =           x                                     xx    |   |    xx           vxxxxxxxxxxxxxxxxxxxxx   ",
   "x                      xxxxxxxxxxxx              x x          xx!!!!!!!!!!!xx                 x               x   ",
   "x  xxxxxx     xxxxxx   x                                       xxxxxxxxxxxxxx                                 x   ",
   "x                      x                       xxxxxxx                      xxxxxxxx         xgx              x   ",
   "x                      x           xx^xx       x  o  x                           x x         x                x   ",
   "xxxxxxxxx              x             x     xxxxx     x      ^^^                    x         x                x   ",
   "x       x  xx^xx       xxxxxxxxx               x    xx      xxx       xxx          xxx       x                x   ",
   "x       x    x   xxx   x                       x     x                             x       xxx                x   ",
   "x    @  x              x                       x     x               x   x         x         x                x   ",
   "x  xxxxxx      xxx xxx x            xxx        xx    x               x   x         x         x                x   ",
   "x             xx  o  xxx          xxx          x     x    xxxxxxx    x   x   xxxxxxxxxxx     x                x   ",
   "x            xx   x   xx            x    o     x     x               x   x # x  o            x                x   ",
   "x            x         x            x  xx#xx   x    xx               x   x!!!x               x                x   ",
   "xxx xxx xxx  xxxx      x            x          x     x               x   xxxxxxx#xxxxxxxxxxxxx                x   ",
   "    x x      x         x      x     xx         x     x               x     o              xxxx                x   ",
   "!!!!x x!!!!!!x      xxxx   x!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =               xxx                x   ",
   "!!!!x x!!!!!!x         x   x!xxxx     xxxxxxxxxx     x!!!!!!!xx!     x                       x                x   ",
   "!!!!x x!!!!!!xxxx      x   x!x            x         xx!!!!!!xx !     xxxxxxxxxxxxxxxxxxxxxxx x%%%%%%%%%%%%    x   ",
   "!!!!x x!!!!!!x         x   x!x                     xx!!!!!!xx  !                           x xxxxxxxxxxxxx    x   ",
   "!!!!x x!!!!!!x      xxxxx  x!xxx^^^xxxxxxxxxxxxxxxxx!!!!!!xx   !                           x                  x   ",
   "!!!!x x!!!!!!x   ooo       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    !                           xxxxxxxxxxxxxxgxxxxx   ",
   "!!!!x x!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  x              xx                                                            x  ",
    "  x  @            x                    xxxxxxxxxxxxxxxxxxxxxx                  x  ",
    "  xxxxxxxxxxxxxx#oxx         o              x                                  x  ",
    "  x             xox         ^^^             x                         x#x      x  ",
    "  x             xox      x!!!!!!!xxx        x      xxxxxxxxxxx                 x  ",
    "  x    x!xx  x!!xox     xx!!!!!!!xxx   ^    x                xxxxxxxxxx xxxxxxxx  ",
    "  x    x!x   x!!xox      xxxxxxxxxxx   ^    x!!!x            x                 x  ",
    "  x    xxx  xxxxxox               o    ^    xxxxxxxxxxxx     x                 x  ",
    "  x      x        x!!!x          xxx   ^                     x  o  ^^^^^^^^    x  ",
    "  x      xxxxxxxxxxxxx                 ^                  x!!x  x              x  ",
    "  x      x              xx!!x          xxxxxxxxxxxxxxxxxxxxxxx                 x  ",
    "  x      x o       xxxxxxxxxx          x          o          x!!!!xxxxxxxxx    x  ",
    "  x      x xxxxxx^^x             xxxx!!x         xxx         x!!!!x            x  ",
    "  x      x x!!!!xxxx o              xxxx      xxxxxxxxx      xxxxxx            x  ",
    "  x      x x!!!!!!!x x     xxx!x       x          o          x                 x  ",
    "  x      x x!!!!!!!x xxxxxxxxxxx       x^^^x     xxx     x^^^x                 x  ",
    "  x                               xxx  xxxxx  ^       ^  xxxxx    xxxxx!!!xxxxxx  ",
    "  x                                           ^       ^      x        xxxxx    x  ",
    "  x^^^^^^xxxxxxxxxxxxxxxxxxxxxxxxxxxxx#xxxxxxxxxxx#xxxxxxxxxxx            x    x  ",
    "  xxxxxxxx                                     x      o      x                 x  ",
    "  x                                            x     xxx     xxxxxxxxxxxx#x    x  ",
    "  x   x!x      xxxxxxxxx^xxxxxxxxxxx                xxxxx    x            x    x  ",
    "  x   xxx              xxx         x!xxxxxxxxxxxxxxxxxxxxxxxxx            x    x  ",
    "  x                                xxx       x!!!x              x         x    x  ",
    "  x                 ooo                                         x#        x    x  ",
    "  x    xx#xx!!!x           x!x           ooo         xxx   x^^^^x!!!!x    x    x  ",
    "  x   x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x    x  ",
    "  x   x                                                                  #x    x  ",
    "  x   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx~zxxxxxx    x  ",
    "  x o x                                                                       #x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx~zxxxxxx  ",
    "                                                                                  "],
  ["                                             ",
   "                                   o         ",
   "     o o ooo o o   o o o ooo oo o  o         ",
   "      o  o o o o   oo oo  o  oo o            ",
   "      o  ooo ooo   o   o ooo o oo  o         ",
   "                                             ",
   "                        @                    ",
   "#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx^",
   "o o o o o o o o o o o o o o o o o o o o o o o"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
